# Pre-commit hooks configuration
# See https://pre-commit.com for more information

default_language_version:
  python: python3

repos:
  # ===== General hooks =====
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      # ファイル末尾の空行を修正
      - id: end-of-file-fixer
        name: ファイル末尾の空行を修正
        exclude: ^(venv/|\.venv/|migrations/|build/|dist/|\.eggs/)
      # 行末の空白を削除
      - id: trailing-whitespace
        name: 行末の空白を削除
        exclude: ^(venv/|\.venv/|migrations/|build/|dist/|\.eggs/)
      # マージコンフリクトのマーカーをチェック
      - id: check-merge-conflict
        name: マージコンフリクトのマーカーをチェック
      # YAMLファイルの構文チェック
      - id: check-yaml
        name: YAMLファイルの構文チェック
        exclude: ^(venv/|\.venv/)
      # JSONファイルの構文チェック
      - id: check-json
        name: JSONファイルの構文チェック
        exclude: ^(venv/|\.venv/|\.vscode/)
      # TOMLファイルの構文チェック
      - id: check-toml
        name: TOMLファイルの構文チェック
        exclude: ^(venv/|\.venv/)
      # 大きなファイルの追加を防ぐ（500KB以上）
      - id: check-added-large-files
        name: 大きなファイルの追加を防ぐ
        args: ['--maxkb=500']
      # Pythonファイルの構文チェック
      - id: check-ast
        name: Pythonファイルの構文チェック
        exclude: ^(venv/|\.venv/|migrations/)
      # デバッグ文の検出
      - id: debug-statements
        name: デバッグ文の検出
        exclude: ^(venv/|\.venv/|migrations/)

  # ===== Lint/Format with status summary (local) =====
  - repo: local
    hooks:
      - id: black-status
        name: Blackによるコードフォーマット（サマリー収集）
        entry: python scripts/hooks/run_check_with_status.py --check black
        language: system
        types: [python]
        exclude: ^(venv/|\.venv/|migrations/|build/|dist/|\.eggs/)


      - id: isort-status
        name: isortによるインポート文の整理（サマリー収集）
        entry: python scripts/hooks/run_check_with_status.py --check isort
        language: system
        types: [python]
        exclude: ^(venv/|\.venv/|migrations/|build/|dist/|\.eggs/)

        args: ["--profile", "black", "--line-length", "79"]

      - id: flake8-status
        name: flake8によるコードチェック（サマリー収集）
        entry: python scripts/hooks/run_check_with_status.py --check flake8
        language: system
        types: [python]
        exclude: ^(venv/|\.venv/|migrations/|build/|dist/|\.eggs/|\.serena/|\.claude/)
        verbose: true
        args:
          - '--max-line-length=79'
          - '--max-complexity=10'

      - id: complexity-check
        name: 複雑度チェック（McCabe）
        entry: python scripts/hooks/run_check_with_status.py --check complexity
        language: system
        types: [python]
        exclude: ^(venv/|\.venv/|migrations/|build/|dist/|\.eggs/|\.serena/|\.claude/)
        verbose: true
        args:
          - '--select=C901'
          - '--max-complexity=10'


      - id: mypy-status
        name: mypyによる型チェック（サマリー収集）
        entry: python scripts/hooks/run_check_with_status.py --check mypy
        language: system
        pass_filenames: false
        verbose: true
        args:
          - --config-file=pyproject.toml
          - --no-incremental
          - app

      - id: coverage-check
        name: コードカバレッジチェック（70%閾値）
        entry: python scripts/hooks/run_check_with_status.py --check coverage
        language: system
        pass_filenames: false
        verbose: true
        args:
          - '--cov=app'
          - '--cov=models'
          - '--cov=services'
          - '--cov=utils'
          - '--cov-fail-under=70'
          - '-m'
          - 'not e2e'

      - id: commit-status-summary
        name: コミット最終サマリー
        entry: python scripts/hooks/final_status_summary.py
        language: system
        pass_filenames: false
        always_run: true

# CI環境での設定
ci:
  autofix_commit_msg: |
    [pre-commit.ci] 自動フォーマット修正

  autofix_prs: true
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit自動更新'
